spring:
  webflux:
    base-path: ${WEATHER_API_BASE_PATH:/v1}

weather:
  default-provider: weatherstack
  circuit-breaker:
    failure-threshold: ${WEATHER_PROVIDER_CIRCUIT_BREAKER_FAILURE_THRESHOLD:3}
    open-duration: ${WEATHER_PROVIDER_CIRCUIT_BREAKER_OPEN_DURATION:30s}
  api:
    resource-path: /weather
    city-param: city

  providers:
    weatherstack:
      base-url: http://api.weatherstack.com
      path: /current
      query-params:
        access_key: ${WEATHERSTACK_API_KEY:YOUR_ACCESS_KEY}
        query: "{location}"
    openweathermap:
      base-url: http://api.openweathermap.org
      path: /data/2.5/weather
      query-params:
        q: "{location},AU"
        units: metric
        appid: ${OPENWEATHERMAP_API_KEY:YOUR_OPENWEATHERMAP_API_KEY}
